JuliaImages/TestImages.jl

README.md
The build failed previously because I had created a branch to update gh-pages and it did not have the travis config file. Github had ignored the travis check for the gh-pages branch itself so I dont know why it doesnt ignore the checks for any branches starting from gh-pages.
This PR will also fix the build failed error due to that branch.
=> Updates Readme to reflect changes in master

.travis.yml, deps/build.jl, src/TestImages.jl
This allows installing the package elsewhere.
Add testing against 0.5 to Travis - this runs the most
recent RC now, release once final tags are done.
=> Use dirname(@__FILE__) instead of Pkg.dir

README.md, src/TestImages.jl
In the upcoming rewrite of Images, this slims down the dependencies for loading image files to just what's needed to load the image.
=> Use FileIO rather than Images to provide `load`

src/TestImages.jl
This also fixes a bug due to a missing "images" directory.
Crosslink https://github.com/JuliaImages/TestImages.jl/commit/4affdea55f406774d1f41b867ff8f90fb622dc9e#commitcomment-19377193.
=> Update URL to JuliaImages

index.html
This is against the `gh-pages` branch, which I didn't remember to update when I first did the move.
=> Fix URLs due to move to JuliaImages

.travis.yml, REQUIRE, appveyor.yml, src/TestImages.jl, test/REQUIRE, test/runtests.jl
For `mri-stack`, the slice spacing is different from the in-plane spacing; it makes sense to encode this so that other suites (e.g., GLVisualize, ImageView, etc) might make use of this.
=> Use AxisArray to encode the slice spacing for mri-stack

.travis.yml, REQUIRE, appveyor.yml
Turns out the CI for this package was never updated to test with v0.6, much less v0.7. This PR updates them to start testing all the supported versions of Julia. 
Currently, tests fail on v0.7 and nightly, and we'll need at least https://github.com/JuliaIO/FileIO.jl/pull/183 before they work, so I've marked them as allowed failures.
=> test v0.6 through nightly

build.jl, index.html
* Checking whether the thumbnail exists and only recreating it if necessary
* White list of file extensions to handle (for example to not work with `.DS_Store` on a Mac.
This adresses #43.
=> Update Thumbnail creation 

.gitignore, .travis.yml, Artifacts.toml, Project.toml, README.md, appveyor.yml, deps/build.jl, src/TestImages.jl, test/runtests.jl
@johnnychen94, I messed this up with #56; consequently, I took #54 (which I had forgotten about) and rebased.
See what you think of this. This version commits to the Artifacts system and thus becomes Julia 1.3+ only. Older Julia versions are supported by previous releases. It also seems to fix https://github.com/JuliaImages/TestImages.jl/pull/54#discussion_r351073517. Also calling it v1.0.0, if that seems appropriate.
=> Version 1.0

Project.toml, test/runtests.jl
@timholy Although I'm pretty sure the problem in https://github.com/JuliaImages/juliaimages.github.io/pull/98 isn't caused by the specific "mandrill" image, it can still be reasonable just to make sure all images are valid.
=> test each files in remotefiles

src/TestImages.jl
I feel inconvenient to do 
```julia
foreach(println, TestImages.remotefiles)
```
when I forget the image names, so I decide to just add them into the docstring of `testimage`
Here's the preview result:
```markdown
The following is a complete list of testimages, you can also check them at https://testimages.juliaimages.org/
* `"autumn_leaves"`
* `"blobs"`
* `"cameraman"`
* `"earth_apollo17"`
* `"fabio_color_256"`
* `"fabio_color_512"`
* `"fabio_gray_256"`
```
=> interpolate remotefiles into docstring of testimage

Project.toml
This is introduced six years ago https://github.com/JuliaImages/TestImages.jl/commit/491bd05599d010fd1a428bc42f0a4d077007c77d and I'm not sure it's still needed now. The test says it's okay to remove it.
=> remove ZipFile dependency

Project.toml, src/TestImages.jl, test/references/abcd_err.txt, test/references/camereman_warning.txt, test/references/leans_err.txt, test/references/leaves_warning.txt, test/references/nonexistence_err.txt, test/runtests.jl, test/utils.jl
The error handling behavior is changed/improved:
* output all candidates with score > 0.5
* if there are candidates with score > 0.8, load the one with the largest score
I'm not string experts, the distance `TokenMax(Levenshtein())` is somehow randomly chosen. In [StringDistances](https://github.com/matthieugomez/StringDistances.jl) it says [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) uses this distance.
```julia
julia> testimage("abcde")
ERROR: ArgumentError: "abcde" not found in `TestImages.remotefiles`.
Stacktrace:
[1] full_imagename(::String) at /Users/jc/Documents/Julia/TestImages.jl/src/TestImages.jl:107
[2] testimage(::String; download_only::Bool, ops::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at …
```
=> give better hints and fallback when filename mismatches

.github/workflows/upload_artifacts.yml, .gitignore, Manifest.toml, Project.toml, build.jl, build_artifacts.jl
This is the first step to address #68 
Manually create and push a tag with name `v*-artifacts` for branch `gh-pages`, and then CI will do the following:
1. generate `images.tar.gz` for all contents in `images/`
2. make a release for this tag
3. upload the artifact
After that, we could then update the URL and hash in `Artifacts.toml` in the `master` branch.
I'm not 100% sure if this workflow works and works nicely, so there might be some noise when I test this.
The `Manifest.toml` is checked in to lock the versions because we don't need to consider compatibility here; all we need is reproducibility.
=> setup artifact CI for automatic generation and upload

index.html
With #73 and #75, all images are now archived in one tarball and provided by PkgServer. The workflow has changed a bit:
1. [contributor] add new images to `images`
2. +[maintainer] when there are new images added, maintainers need to create a `v*-artifacts` tag in `gh-pages` branch
3. +[CI] the artifacts CI will then create a release for this tag, build and upload artifacts to the release
4. [contributor] update `remotefiles` in `src/TestImages.jl` in `master` branch
5. +[contributor] update `Artifacts.toml` in `master` branch; an example `Artifacts.toml` can be found in the release notes, for example in [v1.2.0-artifacts](https://github.com/JuliaImages/TestImages.jl/releases/tag/v1.2.0-artifacts).
6. [maintainer] call `@JuliaRegistrator register` to tag a new release for this
Currently, …
=> update the instruction of how to add new images

Project.toml, src/TestImages.jl, test/runtests.jl
I didn't foresee the name conflict when I port `shepp_logan` in #77 and I have to unexport this symbol right now to appropriately deprecate `Images.shepp_logan`.
The first step of Option 1 in https://github.com/JuliaImages/Images.jl/pull/904#issuecomment-662270008
Given that #77 is released yesterday and I bet nobody is actually using it, I don't plan to tag a breaking release for this.
=> unexport shepp_logan and add depwarn to highContrast

src/TestImages.jl
The changes to the `shepp_logan` implementation follow [this recommendation](https://docs.julialang.org/en/v1/manual/style-guide/#Handle-excess-argument-diversity-in-the-caller). The idea is to standardize the inputs in "small functions" that compile quickly and then compile the big function just once. Obviously this isn't workable for many functions which intrinsically need to handle different types, but in cases like these it makes sense.
Shaves off about 0.25s from the first invocation of `testimage`.
=> Add a few precompile statements

src/TestImages.jl
These changes cut the time needed for the first invocation
of `testimage` by about 140ms. And if precompiltion
ever caches native code, it will help make the latency
nearly zero (nearly all inference has been eliminated).
=> Improve inferrability

src/TestImages.jl, test/runtests.jl
Because of a mistake in the filename comparison, the OffsetArray
wrapper wasn't being applied.
Even though this changes the output type and behavior, this is clearly a bug,
so the fix should not be considered breaking.
=> Fix the PSF image centering

README.md
As we're moving forward to Julia 1.3 and maybe Julia 1.6 stage, a compatibility note might be helpful.
=> Add compatibility note for old Julia versions

src/TestImages.jl, test/runtests.jl
64b0da5 fixes #112 
ImageIO v0.5 introduces TiffImages for tif image loading, which returns a custom array type:
```julia
julia> testimage("camera") |> summary
"512×512 TiffImages.DenseTaggedImage{ColorTypes.Gray{FixedPointNumbers.N0f8}, 2, UInt32, Matrix{ColorTypes.Gray{FixedPointNumbers.N0f8}}}"
```
which, unfortunately, breaks the type assertion.
=> upgrade to newer ImageIO and ColorVectorSpace version

.github/workflows/UnitTest.yml
remove scheduled CI because otherwise Github Action will disable the
whole CI if the repo is not active for 60 days.
only test windows-latest and macos-latest for Julia 1.x release to
save our limited CI resources
=> reduce CI workload

index.html
Fix a badge in https://testimages.juliaimages.org/.
Btw, is there any plan to switch to Documenter.jl?
I thought it will be easy to maintain.
=> Fix ci badge in `gh-pages`

docs/generate_imagelist.jl, docs/make.jl
Just future-proof to not become https://github.com/JuliaImages/juliaimages.github.io/issues/211
- `images/` folder is removed, instead, I use the raw link to the `images/` folder in the `images` branch
- deploy docs with force-push so that we don't increase 4.8M thumbnails data for each of our new commits.
=> compress git history on gh-pages

Artifacts.toml, Project.toml
Main changes in this version:
- Deploy Documenter.jl for this repo
- `RGBA` -> `RGB` for two newly added "sodoku" and "morphology_test" images (#126)
=> TestImages v1.6.1

docs/generate_imagelist.jl, docs/make.jl, docs/src/contributing.md
Here's a screenshot.
We can merge this PR after next artifacts which includes `images/metadata.toml` will be released.
=> Add generation of the note section in the image list

src/TestImages.jl
An alternative to #143. @KristofferC does this look good to you?
I deliberately don't document it here because I'm not going to recommend using it. But if anything, users can easily find and understand what this keyword does by reading the source codes.
closes #143
=> add undocumented nowarn keyword for `testimage`

src/TestImages.jl
As pointed out in https://github.com/ElisabethRoesch/Perspective_Julia_for_Biologists/issues/5, forced conversion of the MRI stack specifically means that users might be surprised that `testimage("mri"; mmap = true)` doesn't actually load the image lazily while it should work well for other TIFFs in the dataset.
This PR removes the forced conversion and it appears to pass all relevant tests @johnnychen94 @timholy
=> Remove forced conversion of mri stack
